local lang = require('mep.org.lang')

describe('mep.org.lang', function()
  describe('to_filetype', function()
    it('lowercases a passthrough language unchanged', function()
      assert.are.equal('python', lang.to_filetype('python'))
      assert.are.equal('python', lang.to_filetype('Python'))
      assert.are.equal('lua', lang.to_filetype('LUA'))
    end)

    it('maps divergent aliases to their real Neovim filetype', function()
      assert.are.equal('javascript', lang.to_filetype('js'))
      assert.are.equal('javascript', lang.to_filetype('JS'))
      assert.are.equal('sh', lang.to_filetype('bash'))
      assert.are.equal('sh', lang.to_filetype('shell'))
      assert.are.equal('cpp', lang.to_filetype('c++'))
      assert.are.equal('cpp', lang.to_filetype('C++'))
      assert.are.equal('cs', lang.to_filetype('c_sharp'))
      assert.are.equal('yaml', lang.to_filetype('yml'))
    end)

    it('returns nil for nil/empty input', function()
      assert.is_nil(lang.to_filetype(nil))
      assert.is_nil(lang.to_filetype(''))
    end)
  end)

  describe('to_extension', function()
    it('reuses mep.org.babel.languages own extension where available', function()
      assert.are.equal('.py', lang.to_extension('python'))
      assert.are.equal('.rb', lang.to_extension('ruby'))
      assert.are.equal('.cpp', lang.to_extension('c++'))
    end)

    it('falls back to .<filetype> for a language babel does not define', function()
      assert.are.equal('.yaml', lang.to_extension('yaml'))
    end)

    it('falls back to .txt for nil/empty input', function()
      assert.are.equal('.txt', lang.to_extension(nil))
      assert.are.equal('.txt', lang.to_extension(''))
    end)
  end)
end)
