local colorizer = require('mep.colorizer')
local config = require('mep.colorizer.config')

local ns = vim.api.nvim_create_namespace('mep_colorizer')

describe('mep.colorizer', function()
  local saved_options

  before_each(function()
    saved_options = vim.deepcopy(config.options)
    config.setup({ debounce_ms = 5 })
  end)

  after_each(function()
    colorizer._reset()
    config.options = saved_options
  end)

  describe('attach/detach', function()
    it('renders immediately on attach', function()
      local buf = vim.api.nvim_create_buf(false, true)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, { '#ff0000' })
      colorizer.attach(buf)
      local marks = vim.api.nvim_buf_get_extmarks(buf, ns, 0, -1, {})
      assert.are.equal(1, #marks)
      assert.is_true(colorizer.is_attached(buf))
      vim.api.nvim_buf_delete(buf, { force = true })
    end)

    it('is idempotent — attaching twice does not double the extmarks', function()
      local buf = vim.api.nvim_create_buf(false, true)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, { '#ff0000' })
      colorizer.attach(buf)
      colorizer.attach(buf)
      local marks = vim.api.nvim_buf_get_extmarks(buf, ns, 0, -1, {})
      assert.are.equal(1, #marks)
      vim.api.nvim_buf_delete(buf, { force = true })
    end)

    it('re-renders (debounced) after a text change', function()
      local buf = vim.api.nvim_create_buf(false, true)
      colorizer.attach(buf)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, { '#ff0000' })
      vim.api.nvim_exec_autocmds('TextChanged', { buffer = buf })

      vim.wait(200, function()
        return #vim.api.nvim_buf_get_extmarks(buf, ns, 0, -1, {}) > 0
      end, 10)

      assert.are.equal(1, #vim.api.nvim_buf_get_extmarks(buf, ns, 0, -1, {}))
      vim.api.nvim_buf_delete(buf, { force = true })
    end)

    it('detach clears extmarks and stops future updates', function()
      local buf = vim.api.nvim_create_buf(false, true)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, { '#ff0000' })
      colorizer.attach(buf)
      colorizer.detach(buf)
      assert.is_false(colorizer.is_attached(buf))
      assert.are.same({}, vim.api.nvim_buf_get_extmarks(buf, ns, 0, -1, {}))
      vim.api.nvim_buf_delete(buf, { force = true })
    end)

    it('respects a configured filetypes allowlist', function()
      config.setup({ debounce_ms = 5, filetypes = { 'css' } })
      local buf = vim.api.nvim_create_buf(false, true)
      vim.bo[buf].filetype = 'lua'
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, { '#ff0000' })
      colorizer.attach(buf)
      assert.is_false(colorizer.is_attached(buf))
      assert.are.same({}, vim.api.nvim_buf_get_extmarks(buf, ns, 0, -1, {}))
      vim.api.nvim_buf_delete(buf, { force = true })
    end)

    it('attaches a matching filetype when filetypes is restricted', function()
      config.setup({ debounce_ms = 5, filetypes = { 'css' } })
      local buf = vim.api.nvim_create_buf(false, true)
      vim.bo[buf].filetype = 'css'
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, { '#ff0000' })
      colorizer.attach(buf)
      assert.is_true(colorizer.is_attached(buf))
      vim.api.nvim_buf_delete(buf, { force = true })
    end)
  end)

  describe('enable/disable', function()
    it('attaches every already-loaded buffer', function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, { '#ff0000' })
      colorizer.enable()
      assert.is_true(colorizer.is_attached(buf))
      vim.api.nvim_buf_delete(buf, { force = true })
    end)

    it('attaches a newly-entered buffer via the global augroup', function()
      colorizer.enable()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, { '#ff0000' })
      vim.api.nvim_exec_autocmds('BufReadPost', { buffer = buf })
      assert.is_true(colorizer.is_attached(buf))
      vim.api.nvim_buf_delete(buf, { force = true })
    end)

    it('disable detaches every buffer and stops the global augroup', function()
      local buf = vim.api.nvim_create_buf(true, false)
      colorizer.enable()
      colorizer.disable()
      assert.is_false(colorizer.is_attached(buf))
      local other = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_exec_autocmds('BufReadPost', { buffer = other })
      assert.is_false(colorizer.is_attached(other))
      vim.api.nvim_buf_delete(buf, { force = true })
      vim.api.nvim_buf_delete(other, { force = true })
    end)
  end)

  describe('setup', function()
    it('calls enable() unconditionally', function()
      local buf = vim.api.nvim_create_buf(true, false)
      colorizer.setup({ debounce_ms = 5 })
      assert.is_true(colorizer.is_attached(buf))
      vim.api.nvim_buf_delete(buf, { force = true })
    end)

    it('returns the resolved options', function()
      local options = colorizer.setup({ mode = 'swatch' })
      assert.are.equal('swatch', options.mode)
    end)
  end)
end)
