local hover = require('mep.chrome.hover')

describe('mep.chrome.hover', function()
  after_each(function()
    hover._reset()
  end)

  describe('enable/disable', function()
    it('enable() turns on mousemoveevent and maps <MouseMove>', function()
      hover.enable()
      assert.is_true(vim.o.mousemoveevent)
      assert.are_not.equal('', vim.fn.maparg('<MouseMove>', 'n'))
    end)

    it('disable() restores mousemoveevent and removes the mapping', function()
      vim.o.mousemoveevent = false
      hover.enable()
      hover.disable()
      assert.is_false(vim.o.mousemoveevent)
      assert.are.equal('', vim.fn.maparg('<MouseMove>', 'n'))
    end)

    it('enable() is idempotent', function()
      assert.has_no.errors(function()
        hover.enable()
        hover.enable()
      end)
    end)
  end)

  describe('set_ranges / clear_ranges', function()
    it('stores and clears per (target, win) ranges without erroring', function()
      local win = vim.api.nvim_get_current_win()
      assert.has_no.errors(function()
        hover.set_ranges('statusline', win, { { widget = {}, start_col = 0, end_col = 3 } })
        hover.clear_ranges('statusline', win)
      end)
    end)
  end)

  describe('tooltip', function()
    it('show_tooltip() opens a floating window, hide_tooltip() closes it', function()
      local wins_before = #vim.api.nvim_list_wins()
      hover.show_tooltip('hello')
      assert.are.equal(wins_before + 1, #vim.api.nvim_list_wins())
      hover.hide_tooltip()
      assert.are.equal(wins_before, #vim.api.nvim_list_wins())
    end)

    it('show_tooltip() accepts a list of lines', function()
      assert.has_no.errors(function()
        hover.show_tooltip({ 'line one', 'line two' })
      end)
      hover.hide_tooltip()
    end)

    it('hide_tooltip() is safe with no open tooltip', function()
      assert.has_no.errors(function()
        hover.hide_tooltip()
      end)
    end)

    it('show_tooltip() replaces a previous tooltip rather than stacking', function()
      local wins_before = #vim.api.nvim_list_wins()
      hover.show_tooltip('one')
      hover.show_tooltip('two')
      assert.are.equal(wins_before + 1, #vim.api.nvim_list_wins())
      hover.hide_tooltip()
    end)
  end)

  describe('_reset()', function()
    it('clears ranges, hides any tooltip, and disables', function()
      hover.enable()
      hover.show_tooltip('x')
      hover._reset()
      assert.are.equal('', vim.fn.maparg('<MouseMove>', 'n'))
    end)
  end)
end)
