local parse = require('mep.snippet.parse')

describe('mep.snippet.parse', function()
  describe('parse', function()
    it('parses plain text with no tabstops', function()
      local parts = parse.parse('hello world')
      assert.are.same({ { type = 'text', text = 'hello world' } }, parts)
    end)

    it('parses a bare numbered tabstop', function()
      local parts = parse.parse('foo $1 bar')
      assert.are.equal(3, #parts)
      assert.are.same({ type = 'text', text = 'foo ' }, parts[1])
      assert.are.same({ type = 'tabstop', index = 1, placeholder = nil }, parts[2])
      assert.are.same({ type = 'text', text = ' bar' }, parts[3])
    end)

    it('parses ${N} the same as $N', function()
      local parts = parse.parse('${2}')
      assert.are.same({ { type = 'tabstop', index = 2, placeholder = nil } }, parts)
    end)

    it('parses ${N:default} with placeholder text', function()
      local parts = parse.parse('${1:name}')
      assert.are.same({ { type = 'tabstop', index = 1, placeholder = 'name' } }, parts)
    end)

    it('parses $0 as an ordinary tabstop index', function()
      local parts = parse.parse('$0')
      assert.are.same({ { type = 'tabstop', index = 0, placeholder = nil } }, parts)
    end)

    it('parses a full multi-tabstop function body', function()
      local parts = parse.parse('function $1($2)\n\t$0\nend')
      assert.are.equal(7, #parts)
      assert.are.equal('tabstop', parts[2].type)
      assert.are.equal(1, parts[2].index)
      assert.are.equal('tabstop', parts[4].type)
      assert.are.equal(2, parts[4].index)
      assert.are.equal('tabstop', parts[6].type)
      assert.are.equal(0, parts[6].index)
    end)

    it('unescapes \\$ to a literal dollar sign', function()
      local parts = parse.parse('cost: \\$5')
      assert.are.same({ { type = 'text', text = 'cost: $5' } }, parts)
    end)

    it('treats an unterminated ${ as literal text', function()
      local parts = parse.parse('${1')
      assert.are.same({ { type = 'text', text = '${1' } }, parts)
    end)

    it('treats a trailing $ with nothing after it as literal text', function()
      local parts = parse.parse('foo$')
      assert.are.same({ { type = 'text', text = 'foo$' } }, parts)
    end)
  end)

  describe('render', function()
    it('renders plain text with no tabstops', function()
      local lines, tabstops = parse.render(parse.parse('hello'), '')
      assert.are.same({ 'hello' }, lines)
      assert.are.same({}, tabstops)
    end)

    it('computes a single-line tabstop\'s column span', function()
      local lines, tabstops = parse.render(parse.parse('foo $1 bar'), '')
      assert.are.same({ 'foo  bar' }, lines)
      assert.are.equal(1, #tabstops)
      assert.are.same({ index = 1, lnum = 0, col_start = 4, col_end = 4 }, tabstops[1])
    end)

    it('includes a placeholder\'s default text in the rendered line and its span', function()
      local lines, tabstops = parse.render(parse.parse('${1:name}!'), '')
      assert.are.same({ 'name!' }, lines)
      assert.are.same({ index = 1, lnum = 0, col_start = 0, col_end = 4 }, tabstops[1])
    end)

    it('re-indents continuation lines to match the given indent', function()
      local lines, tabstops = parse.render(parse.parse('function $1($2)\n\t$0\nend'), '    ')
      assert.are.same({ 'function ()', '    \t', '    end' }, lines)
      assert.are.equal(3, #tabstops)
      assert.are.same({ index = 1, lnum = 0, col_start = 9, col_end = 9 }, tabstops[1])
      assert.are.same({ index = 2, lnum = 0, col_start = 10, col_end = 10 }, tabstops[2])
      assert.are.same({ index = 0, lnum = 1, col_start = 5, col_end = 5 }, tabstops[3])
    end)
  end)
end)
