local registry = require('mep.snippet.registry')

describe('mep.snippet.registry', function()
  after_each(function()
    registry._reset()
  end)

  describe('add / get', function()
    it('returns an empty list for a filetype with nothing registered', function()
      assert.are.same({}, registry.get('lua'))
    end)

    it('returns everything registered under a filetype', function()
      registry.add('lua', { { trigger = 'fn', body = 'function $1()\n\t$0\nend' } })
      local list = registry.get('lua')
      assert.are.equal(1, #list)
      assert.are.equal('fn', list[1].trigger)
    end)

    it('is additive across multiple add() calls for the same filetype', function()
      registry.add('lua', { { trigger = 'fn', body = 'a' } })
      registry.add('lua', { { trigger = 'if', body = 'b' } })
      assert.are.equal(2, #registry.get('lua'))
    end)

    it('keeps snippets separate per filetype', function()
      registry.add('lua', { { trigger = 'fn', body = 'lua body' } })
      registry.add('python', { { trigger = 'fn', body = 'python body' } })
      assert.are.equal(1, #registry.get('lua'))
      assert.are.equal(1, #registry.get('python'))
    end)
  end)

  describe('find', function()
    it('finds a registered trigger', function()
      registry.add('lua', { { trigger = 'fn', body = 'function $1()\n\t$0\nend' } })
      local snip = registry.find('lua', 'fn')
      assert.is_not_nil(snip)
      assert.are.equal('function $1()\n\t$0\nend', snip.body)
    end)

    it('returns nil for an unregistered trigger', function()
      assert.is_nil(registry.find('lua', 'nope'))
    end)

    it('returns nil for a trigger registered under a different filetype', function()
      registry.add('python', { { trigger = 'fn', body = 'x' } })
      assert.is_nil(registry.find('lua', 'fn'))
    end)

    it('last-added wins on a duplicate trigger within the same filetype', function()
      registry.add('lua', { { trigger = 'fn', body = 'first' } })
      registry.add('lua', { { trigger = 'fn', body = 'second' } })
      assert.are.equal('second', registry.find('lua', 'fn').body)
    end)
  end)

  describe('_reset', function()
    it('forgets every registered snippet', function()
      registry.add('lua', { { trigger = 'fn', body = 'x' } })
      registry._reset()
      assert.are.same({}, registry.get('lua'))
    end)
  end)
end)
