local protocol = require('mep.dap.protocol')

describe('mep.dap.protocol', function()
  describe('encode', function()
    it('frames a payload with a correct Content-Length header', function()
      local framed = protocol.encode({ seq = 1, type = 'request', command = 'initialize' })
      local body = vim.json.encode({ seq = 1, type = 'request', command = 'initialize' })
      assert.are.equal(string.format('Content-Length: %d\r\n\r\n%s', #body, body), framed)
    end)

    it('counts bytes, not characters, for a multi-byte body', function()
      local framed = protocol.encode({ text = 'héllo' })
      local body = vim.json.encode({ text = 'héllo' })
      local length = tonumber(framed:match('Content%-Length: (%d+)'))
      assert.are.equal(#body, length)
      assert.are_not.equal(vim.fn.strchars(body), length) -- sanity: body has a multi-byte char
    end)
  end)

  describe('parse_messages', function()
    it('parses a single complete message', function()
      local framed = protocol.encode({ seq = 1, type = 'event', event = 'initialized' })
      local messages, remainder = protocol.parse_messages(framed)
      assert.are.equal(1, #messages)
      assert.are.equal('initialized', messages[1].event)
      assert.are.equal('', remainder)
    end)

    it('parses two messages arriving back to back', function()
      local framed = protocol.encode({ seq = 1 }) .. protocol.encode({ seq = 2 })
      local messages, remainder = protocol.parse_messages(framed)
      assert.are.equal(2, #messages)
      assert.are.equal(1, messages[1].seq)
      assert.are.equal(2, messages[2].seq)
      assert.are.equal('', remainder)
    end)

    it('leaves an incomplete body in the remainder', function()
      local framed = protocol.encode({ seq = 1, hello = 'world' })
      local cut = framed:sub(1, #framed - 5)
      local messages, remainder = protocol.parse_messages(cut)
      assert.are.same({}, messages)
      assert.are.equal(cut, remainder)
    end)

    it('resumes correctly once the rest of a split message arrives', function()
      local framed = protocol.encode({ seq = 1, hello = 'world' })
      local first_half = framed:sub(1, 20)
      local second_half = framed:sub(21)
      local messages, remainder = protocol.parse_messages(first_half)
      assert.are.same({}, messages)
      messages, remainder = protocol.parse_messages(remainder .. second_half)
      assert.are.equal(1, #messages)
      assert.are.equal('world', messages[1].hello)
      assert.are.equal('', remainder)
    end)

    it('leaves an incomplete header in the remainder', function()
      local partial = 'Content-Length: 4'
      local messages, remainder = protocol.parse_messages(partial)
      assert.are.same({}, messages)
      assert.are.equal(partial, remainder)
    end)

    it('drops a message whose body fails to decode as JSON, but keeps parsing after it', function()
      local bad_body = 'not json'
      local bad = string.format('Content-Length: %d\r\n\r\n%s', #bad_body, bad_body)
      local good = protocol.encode({ seq = 42 })
      local messages, remainder = protocol.parse_messages(bad .. good)
      assert.are.equal(1, #messages)
      assert.are.equal(42, messages[1].seq)
      assert.are.equal('', remainder)
    end)

    it('returns an empty buffer for empty input', function()
      local messages, remainder = protocol.parse_messages('')
      assert.are.same({}, messages)
      assert.are.equal('', remainder)
    end)
  end)
end)
