local test_runners = require('mep.activitybar.test_runners')

describe('mep.activitybar.test_runners', function()
  it('exposes every runner by name', function()
    assert.is_not_nil(test_runners.registry.go)
    assert.is_not_nil(test_runners.registry.cargo)
    assert.is_not_nil(test_runners.registry.jest)
    assert.is_not_nil(test_runners.registry.pytest)
    assert.is_not_nil(test_runners.registry.busted)
  end)

  describe('resolve', function()
    it('detects go.mod over the busted default', function()
      local dir = vim.fn.resolve(vim.fn.tempname())
      vim.fn.mkdir(dir, 'p')
      vim.fn.writefile({ 'module x' }, dir .. '/go.mod')
      assert.are.equal(test_runners.registry.go, test_runners.resolve(dir))
    end)

    it('detects Cargo.toml', function()
      local dir = vim.fn.resolve(vim.fn.tempname())
      vim.fn.mkdir(dir, 'p')
      vim.fn.writefile({ '[package]' }, dir .. '/Cargo.toml')
      assert.are.equal(test_runners.registry.cargo, test_runners.resolve(dir))
    end)

    it('falls back to busted when nothing else matches', function()
      local dir = vim.fn.resolve(vim.fn.tempname())
      vim.fn.mkdir(dir, 'p')
      assert.are.equal(test_runners.registry.busted, test_runners.resolve(dir))
    end)

    it('prefers the ORDER-first match when multiple markers are present', function()
      local dir = vim.fn.resolve(vim.fn.tempname())
      vim.fn.mkdir(dir, 'p')
      vim.fn.writefile({ 'module x' }, dir .. '/go.mod')
      vim.fn.writefile({ '[package]' }, dir .. '/Cargo.toml')
      assert.are.equal(test_runners.registry.go, test_runners.resolve(dir))
    end)
  end)
end)
